# Generated by Django 5.2.8 on 2025-11-18 14:35

import django.db.models.deletion
import laboratory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresult',
            options={'verbose_name': 'جواب آژمایش', 'verbose_name_plural': 'جواب های آزمایش ها'},
        ),
        migrations.AlterField(
            model_name='labresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='file',
            field=models.FileField(upload_to=laboratory.models.lab_file_path, verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='serial_number',
            field=models.CharField(editable=False, max_length=6, unique=True, verbose_name='شماره سریال'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
