# Generated by Django 5.1.7 on 2025-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('PCS', 'عدد'), ('GR', 'گرم'), ('KG', 'کیلوگرم'), ('LTR', 'لیتر'), ('M', 'متر'), ('CM', 'سانتی\u200cمتر'), ('BOX', 'بسته')], default='PCS', max_length=20, verbose_name='واحد اندازه\u200cگیری'),
        ),
    ]
