# Generated by Django 5.1.7 on 2025-11-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_product_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('warehouse', 'product')},
        ),
    ]
