# Generated by Django 5.1.7 on 2025-11-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_stockmovement_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
    ]
