# Generated by Django 5.2.8 on 2025-11-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_gallerypage_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
    ]
