# Generated by Django 5.2.8 on 2025-11-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
    ]
