# Generated by Django 5.2.8 on 2025-11-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='article.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='article.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام تگ'),
        ),
    ]
