# Generated by Django 5.2.8 on 2025-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_remove_tag_slug_articlepage_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article.tag', verbose_name='تگ\u200cها'),
        ),
    ]
