# Generated by Django 5.2.8 on 2025-11-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_alter_tag_options_articletag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='tag',
        ),
    ]
