# Generated by Django 5.2.8 on 2025-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_remove_articlepage_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'تگ', 'verbose_name_plural': 'تگ\u200cها'},
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
