# Generated by Django 5.2.8 on 2025-11-20 16:14

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_tag_options_articlepage_tag_delete_articletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='tag',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='articles', to='article.tag', verbose_name='تگ\u200cها'),
        ),
    ]
