# Generated by Django 5.2.8 on 2025-11-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_alter_articlepage_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='tag',
            new_name='tags',
        ),
    ]
