# Generated by Django 5.2.8 on 2025-11-21 18:28

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_rename_tag_articlepage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='display_name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام نمایشی'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.articlepage', verbose_name='مقاله'),
        ),
    ]
