# Generated by Django 5.2.8 on 2025-11-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_remove_comment_user_comment_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='نام نمایشی'),
        ),
    ]
