# Generated by Django 5.2.8 on 2025-11-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_alter_comment_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده؟'),
        ),
    ]
