# Generated by Django 5.2.8 on 2025-11-22 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_alter_comment_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.articlepage', verbose_name='مقاله'),
        ),
    ]
