# Generated by Django 5.2.8 on 2025-11-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_remove_comment_sort_order_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='display_name',
            field=models.CharField(help_text='نامی که در کنار نظر نمایش داده می\u200cشود.', max_length=100, verbose_name='نام نمایشی'),
        ),
    ]
